title: 刘晁企
logo: /photos/logo.jpeg
description: "我滑向冰球要去的地方，而不是它曾经去过的地方"
remote_theme: BDHU/minimalist
color-scheme: auto

sidebar:
  - name: 主页
    link: https://chaoqi-liu.github.io
  - name: 教育
    link: https://chaoqi-liu.github.io/education/overview
  - name: 经历
    link: https://chaoqi-liu.github.io/experience/overview
  - name: 荣誉及奖项
    link: https://chaoqi-liu.github.io/honors&awards
